name: Sync Calendar

on:
  schedule:
    - cron: "*/30 * * * *"   # 30分ごと更新
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install deps
      run: npm install

    - name: Generate schedule.txt
      env:
        FIREBASE_KEY: ${{ secrets.FIREBASE_KEY }}
      run: node scripts/generate.js

    - name: Commit files
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "auto update" || exit 0
        git push